from typing import List, Optional
from pydantic import BaseModel, Field, ConfigDict


class ScenePlanData(BaseModel):
    """Structured data model for an individual scene within a generation plan."""
    scene_index: int = Field(..., ge=1, description="1-based scene sequence order")
    duration_seconds: float = Field(..., ge=1.0, le=60.0, description="Duration of this scene in seconds")
    description: str = Field(..., description="High-level narrative description of action in scene")
    visual_prompt: str = Field(..., description="Detailed AI image/video generation prompt")
    negative_prompt: Optional[str] = Field("blurry, low quality, distortion", description="Negative prompt tags")
    narration_text: Optional[str] = Field(None, description="Voiceover or character dialogue script")
    narration_voice: Optional[str] = Field("natural", description="Voice persona style")
    background_audio_prompt: Optional[str] = Field(None, description="Sound effect or ambient audio prompt")
    transition: str = Field("cut", description="Transition effect to next scene (e.g. cut, fade, dissolve)")

    model_config = ConfigDict(from_attributes=True)


class GenerationPlanData(BaseModel):
    """Structured data model for a complete video generation plan generated by AI."""
    intent: str = Field(..., description="Project-level creative goal and narrative vision")
    title: str = Field(..., description="Creative title for the generated video")
    style: str = Field(..., description="Visual aesthetic style preset")
    target_duration_seconds: int = Field(..., ge=5, le=120, description="Total target duration in seconds")
    aspect_ratio: str = Field("16:9", description="Video aspect ratio")
    scenes: List[ScenePlanData] = Field(..., min_length=1, description="Sequential list of scenes")
    estimated_workload: int = Field(..., ge=1, description="Estimated visual generation workload units")

    model_config = ConfigDict(from_attributes=True)
